root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o main.exe ./cmd/api"
bin = "main.exe"
full_bin = "main.exe"
include_ext = ["go"]
exclude_dir = ["tmp", "mongodb_data"]
delay = 1000

[screen]
clear_on_rebuild = true